// <auto-generated />
namespace Tech_News.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changelongtointonarticletable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changelongtointonarticletable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110170220195_change long to int on article table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
