// <auto-generated />
namespace Tech_News.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class altertablecommentaddforeignkeyarticle_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altertablecommentaddforeignkeyarticle_id));
        
        string IMigrationMetadata.Id
        {
            get { return "202110210111131_alter table comment add foreignkey article_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
