// <auto-generated />
namespace Tech_News.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addcreate_atandupdate_atfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcreate_atandupdate_atfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202110170159043_Add create_at and update_at file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
